GET http://localhost:3000
### REGIST USER
POST http://localhost:3000/api/v1/user/register
Content-Type: application/json

{
    "name":"aldi",
    "email":"200401141@student.umri.ac.id",
    "password":"password123",
    "password_confirmation":"password123"
}


###
POST http://localhost:3000/api/v1/user/login
Content-Type: application/json

{
    "email":"200401141@student.umri.ac.id",
    "password":"password123"
}


###
GET http://localhost:3000/api/v1/user/whoami
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImlhdCI6MTcwMDQ4MjEwN30.4uDQecAka801Ta8-DufKh5irxiC16ugvCAbxDNLsIaw
